### ======================================== BLOGS  ======================================== ###
### Get all blogs
GET http://localhost:3001/api/blogs
Accept: application/json

### Get blog 2
GET http://localhost:3001/api/blogs/2
Accept: application/json

### Create blog 1
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc3MjExMTUzMX0.dFb1iZ0a52FbrflHcvVoejE6xdQXXD4F5-9s6QS72yE

{
  "author": "John Doe",
  "title": "Getting Started with Sequelize",
  "url": "https://example.com/sequelize-guide",
  "likes": 5,
  "date": "12:00:00",
  "year_written": 2006
}

### Create blog 2
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc3MjExMTUzMX0.dFb1iZ0a52FbrflHcvVoejE6xdQXXD4F5-9s6QS72yE

{
  "author": "Jane Smith",
  "title": "Understanding REST APIs",
  "url": "https://example.com/rest-api",
  "likes": 2,
  "date": "14:30:00",
  "year_written": 1950
}

### Create blog 3
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc3MjExMTUzMX0.dFb1iZ0a52FbrflHcvVoejE6xdQXXD4F5-9s6QS72yE

{
  "author": "Alex Johnson",
  "title": "PostgreSQL Basics",
  "url": "https://example.com/postgresql-basics",
  "likes": 0,
  "date": "16:45:00"
}

### Create blog 4 - Error
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Alex Johnson",
  "url": "https://example.com/postgresql-basics",
  "likes": 0,
  "date": "16:45:00"
}

### Delete blog 2
DELETE http://localhost:3001/api/blogs/2
Content-Type: application/json

### Like blog 1
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

### ======================================== USERS  ======================================== ###

### Get all users
GET http://localhost:3001/api/users

### Create user 
POST http://localhost:3001/api/users
Content-Type: application/json

{
  	"username": "mluukkai@example.com",
  	"name": "Matti Luukkainen",
  	"password": "secret"
}

### Create user 2
POST http://localhost:3001/api/users
Content-Type: application/json

{
  	"username": "jakousa@example.com",
  	"name": "Jami Kousa",
    "password": "secret",
  	"disabled": true
}

### Create user 3
POST http://localhost:3001/api/users
Content-Type: application/json

{
  	"username": "ousa@example.com",
  	"name": "Outi Savolainen",
	"password": "secret",
  	"admin": true
}

### Login user 
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mluukkai@example.com",
  "password": "secret"
}

### Edit user name (not username)
PUT http://localhost:3001/api/users/martinverniere
Content-Type: application/json

{
  "name": "Edited"
}

### Change is enabled user 
PUT http://localhost:3001/api/users/jakousa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im91c2EyIiwiaWQiOjUsImlhdCI6MTc3MjAyNjc3OX0.g-BJ6DLS3SNdnFUOTvWqNSjckgfbmJfiiQYyA_9Gxmo

{
  "disabled": false
}